name: pysnowpark
channels:
  - https://repo.anaconda.com/pkgs/snowflake
  - nodefaults
dependencies:
  - python=3.8
  - pandas
  - snowflake-snowpark-python[pandas]
  - pip
  - ipython
  - ipykernel
  - pip:
    # Snowflake
    - snowflake-cli-labs
